remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Nij.iCal
description: にじさんじ非公式カレンダー <br />/ Nijisanji Unofficial Calendar
show_downloads: false
logo: /imgs/logo.png
github:
  is_project_page: false
twitter:
  card: summary
  username: "@nijical2434"
